### ISSUE TITLE
Freeze when using "yank" function

### ISSUE THREAD

**Issue by lheckemann** [utdemir/nix-tree#25] opened 2021-09-02 12:10 UTC
Whenever I use the yank function, the store path is copied to the clipboard correctly, but nix-tree stops responding to any further input. I'm not sure how to debug any further, any suggestions?

**Comment by utdemir** [comment] 2021-09-02 22:13
Oh, that's annoying, but I think I have an idea of what might be happening. 

Yank functionality is implemented via trying to run a set of shell commands, in this order:

https://github.com/utdemir/nix-tree/blob/6358dedbafb91241c1a1caab2ba9b56b881da0fe/src/Clipboard.hs#L11-L16

I have `xsel` on my system and it works fine for me, but I think you might be using another one which might be configured incorrectly and not terminating, blocking the main thread.

Does it make sense to you? You can try running `echo foobar | <cmd>` for each of the above comments, and see if they terminate correctly; and if you see something which doesn't work, feel free to comment here or send a PR.

There're things we can do to mitigate this issue freezing the entire app; we can put a timeout to the command, or just run it outside of the main thread. I'll implement one of them, but I'd still appreciate if you could try to spot which command is incorrect.

**Comment by utdemir** [comment] 2021-09-04 10:13
I put a timeout on the command for the yank action, which is not a solution but should still be better than freezing.

https://github.com/utdemir/nix-tree/commit/bb7723123fdd06469ca15cf9e1f09865253e37b6

Keeping the issue open since I don't exactly know if this is the problem, and even if it is we still have to figure out why it hangs.

**Comment by lheckemann** [comment] 2021-12-21 14:16
The timeout doesn't work as desired because [System.Timeout can only interrupt Haskell code](https://hackage.haskell.org/package/base-4.8.2.0/docs/System-Timeout.html).

There is a wl-copy process running starting from when I press y, but `nix-tree`'s timeout doesn't take effect: if I kill wl-copy or it exits because something else is copied to the clipboard, nix-tree will report that it timed out, but long after the specified timeout has expired.

What I don't understand is why it's waiting for wl-copy to complete at all: wl-copy forks itself to run in the background (to service any paste requests), but the main process exits almost immediately with a success exit code. I'd expect that `nix-tree` receives this success code, interprets that as a success, and continues to operate normally. Maybe we're using System.Process.Typed wrong?

**Comment by utdemir** [comment] 2021-12-21 21:26
Very interesting. Thank you for delving in @lheckemann.

> System.Timeout can only interrupt Haskell code.

This is good to know, but my mental model was that System.Process runs the process on a separate Haskell thread and communicates it via STM; so it should be interruptible as it's not a long-running FFI call.

> Maybe we're using System.Process.Typed wrong?

Maybe. But we are not doing anything fancy, other than calling `readProcess`:

https://github.com/utdemir/nix-tree/blob/bb7723123fdd06469ca15cf9e1f09865253e37b6/src/Clipboard.hs#L21-L24

But clearly there's something I'm missing in this picture, as I can not explain why it blocks.

So, I'll have a look at it later this weekend, and try to reproduce the issue (but do feel free to experiment more/fix if you're feel like it)

**Comment by utdemir** [comment] 2021-12-25 23:57
@lheckemann I just checked, and it seems like grabbing stdout (and stderr) of the child process was causing the `System.Timeout.timeout` to not work. I made https://github.com/utdemir/nix-tree/commit/27e7c2ccfc0d7955f5e2adccc5e2568940277049 which just inherits stdout and stderr, which fixed the timeout.

But I do not know whether it fixed the `wl-copy` issue. Can you have a look? Otherwise, I do not have a Wayland machine so I don't how I can debug it; but do let me know if you have an idea I should try out.

**Comment by bew** [comment] 2021-12-26 00:56
Tested it on my side, on X11 using xclip (it was freezing for me as well), and now it doesn't freeze anymore :+1:

**Comment by utdemir** [comment] 2022-01-28 22:36
I'm tentatively marking this as done as per @bew's comment; @lheckemann please feel free to reopen it if the new version doesn't solve your issue!

**Closed by utdemir** 2022-01-28 22:36 UTC

**Comment by lheckemann** [comment] 2022-01-29 08:42
Works wonderfully, thanks!
