### ISSUE TITLE
Cannot search for dependencies that have a 'q' in their name

### ISSUE THREAD

**Issue by piegamesde** [utdemir/nix-tree#21] opened 2021-03-31 22:18 UTC
Because hitting 'q' closes the search mode ;)

**Comment by utdemir** [comment] 2021-03-31 23:11
Yeah that was a funny bug :). But it should be fixed on version `1.2.0`, which is already at `nixpkgs-unstable`, however it's not in `nixpkgs-stable` yet.

Could you try updating your `nix-tree`?

**Comment by utdemir** [comment] 2021-04-05 04:29
I'm going to close this issue because I _believe_ it is already fixed. Please do re-open it if you can reproduce it on newer versions.

**Closed by utdemir** 2021-04-05 04:29 UTC
